/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import clases.Insumo;

import javax.swing.table.DefaultTableModel;
import com.itextpdf.text.Document;
import javax.swing.text.*;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.*;
import controlador.Controlador;
import PDF.PDF;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Desktop;
import java.io.File;
import java.io.FileOutputStream;
import java.sql.*;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import modelo.Modelo;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Hector
 */
public class frmReporteInventario extends javax.swing.JFrame {
    frmMenuGeneral menu;
    DefaultTableModel dtm;
    String pdfFilePath = "D:\\ONEDRIVEHECTORUTP\\OneDrive - Universidad Tecnologica del Peru\\Reportes PDF";
    File file = new File(pdfFilePath);

    /**
     * Creates new form frmReporte
     */
    
   
    
    public frmReporteInventario(frmMenuGeneral menu) {
        initComponents();
        this.menu = menu;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableModel = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnGenerarReportePDF = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insumos por agotarse", "Unidades restantes"
            }
        ));
        jScrollPane1.setViewportView(tableModel);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insumos por vencer", "#Días para su vencimiento"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        btnGenerarReportePDF.setText("Generar Reporte PDF");
        btnGenerarReportePDF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarReportePDFActionPerformed(evt);
            }
        });

        btnRegresar.setText("Regresar");
        btnRegresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegresarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addComponent(btnGenerarReportePDF))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(btnRegresar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addComponent(btnGenerarReportePDF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarReportePDFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarReportePDFActionPerformed
        // TODO add your handling code here:
           // Obtener los insumos desde la base de datos
    
    Controlador controlador = new Controlador();
    List<Insumo> insumos = controlador.getInsumos();
      
    
    
    
    
    // Definir el nombre del archivo PDF
    String pdfFilePath = "C:\\Users\\oscar\\OneDrive\\Documentos\\CICLO VI\\Integrador I\\INTEGRADOR-AV3\\Reportes PDF\\Reportes_PDF.pdf";
    
    // Crear el documento PDF
    Document document = new Document();
    try {
        // Crear escritor de PDF
        PdfWriter.getInstance(document, new FileOutputStream(pdfFilePath));
        
        // Abrir el documento
        document.open();
        
        // Añadir título al PDF
        document.add(new Paragraph("Reporte de Inventario Insumos por agotarse - ZariSpa"));
        document.add(new Paragraph("Fecha: " + new java.util.Date()));
        document.add(new Paragraph(" "));
        
        // Crear tabla con 4 columnas (correspondientes a los datos de la tabla INVENTARIO)
        PdfPTable table = new PdfPTable(4);
        table.setWidthPercentage(100);
        
        // Añadir los encabezados de la tabla
        table.addCell("Código");
        table.addCell("Nombre");
        table.addCell("Cantidad");
        table.addCell("Categoría");
        
        // Añadir los datos de los insumos
        for (Insumo insumo : insumos) {
            table.addCell(insumo.getCodigo());
            table.addCell(insumo.getNombre());
            table.addCell(String.valueOf(insumo.getCantidad()));
            table.addCell(insumo.getCategoria());
        }
        
        // Añadir la tabla al documento PDF
        document.add(table);
        
        // Cerrar el documento
        document.close();
        
        // Mostrar un mensaje de éxito
        JOptionPane.showMessageDialog(this, "Reporte PDF generado exitosamente en " + pdfFilePath);
        
    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error al generar el reporte PDF: " + e.getMessage());
    }
    }//GEN-LAST:event_btnGenerarReportePDFActionPerformed

    private void btnRegresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegresarMouseClicked
        // TODO add your handling code here:
        this.dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnRegresarMouseClicked

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarReportePDF;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tableModel;
    // End of variables declaration//GEN-END:variables
}
